# Matrix Debounce
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=15
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=30

# Force Bluetooth ON
CONFIG_ZMK_BLE=y

# Force Maximum Bluetooth Signal Strength
# CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Override the broadcast name to something unmistakable
CONFIG_ZMK_KEYBOARD_NAME="GHOST_HUNTER"

# Enable Pointing Device Support
# CONFIG_ZMK_POINTING=y

# Enable ZMK Sleep functionality
CONFIG_ZMK_SLEEP=n

# 1. Idle Timeout (10 seconds)
# Keyboard stays connected, but stops scanning matrix aggressively to save power. Wakes instantly.
CONFIG_ZMK_IDLE_TIMEOUT=10000

# 2. Deep Sleep Timeout (15 minutes)
# Bluetooth radio turns off. Requires a keypress and a 3-5 second wait to wake up.
#CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=30000