# Matrix Debounce
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=15
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=30

# Force Bluetooth ON
CONFIG_ZMK_BLE=y

# Force Maximum Bluetooth Signal Strength
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Override the broadcast name to something unmistakable
CONFIG_ZMK_KEYBOARD_NAME="GHOST_HUNTER"